site_name: Calibration Suite Docs
repo_url: https://github.com/slaclab/beamtime-calibration-suite

nav:
  - Home: index.md
  - Setup: setup.md
  - Testing: testing.md
  - Environment: environment.md
  - Learning Git: learning_git.md
  - Git Workflow: workflow.md
  - Useful Git Commands: commands.md
  - Logging: logging.md
  - Script Usage: usage.md
theme:
  name: 'readthedocs'

plugins:
  - search
